name: "Release"

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - "**"

jobs:
  release:
    name: "Release"

    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e  # v2
      - uses: gradle/gradle-build-action@v2
      - run: gradle clean test
      - run: gradle clean assemble -Dorg.gradle.project.version="${GITHUB_REF#refs/tags/}"
      - name: "Determine tag"
        run: "echo \"RELEASE_TAG=${GITHUB_REF#refs/tags/}\" >> $GITHUB_ENV"
      - name: "Determine filename"
        run: "echo \"PLUGIN_JAR_NAME=getsentry-webhook-notifier-${GITHUB_REF#refs/tags/}.jar\" >> $GITHUB_ENV"
      - name: "Create release"
        uses: "actions/github-script@v5"
        with:
          script: |
            try {
              const release = await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: process.env.RELEASE_TAG,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: process.env.RELEASE_TAG,
              });
              await github.rest.repos.uploadReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: release.data.id,
                name: $PLUGIN_JAR_NAME,
                data: await fs.readFileSync(`build/libs/${process.env.PLUGIN_JAR_NAME}`)
              });
            } catch (error) {
              core.setFailed(error.message);
            }
