name: "Release"

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - "**"

jobs:
  release:
    name: "Release"

    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e  # v2
      - uses: gradle/gradle-build-action@v2
      - run: gradle clean test
      - run: gradle clean assemble -Dorg.gradle.project.version="${GITHUB_REF#refs/tags/}"
      - name: "Determine tag"
        run: "echo \"RELEASE_TAG=${GITHUB_REF#refs/tags/}\" >> $GITHUB_ENV"
      - name: "Create release"
        uses: "actions/github-script@v5"
        with:
          script: |
            const fs = require('fs');
            try {
              const tag = context.ref.replace("refs/tags/", "");

              // Get release for this tag
              const release = await github.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag
              });

              await github.rest.repos.uploadReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: release.data.id,
                name: $PLUGIN_JAR_NAME,
                data: await fs.readFileSync(`build/libs/getsentry-webhook-notifier-${tag}.jar`),
              });
            } catch (error) {
              core.setFailed(error.message);
            }
